In [1]:
import numpy as np

In [2]:
num = np.array([13,56,34,78,10])

In [3]:
print(num)

[13 56 34 78 10]


In [4]:
num

array([13, 56, 34, 78, 10])

In [5]:
num.dtype

dtype('int32')

In [6]:
type(num)

numpy.ndarray

In [7]:
num.ndim

1

In [8]:
num2 =np.array(['praju',26 ,45, 65, 35,0.45])

In [9]:
num2.dtype

dtype('<U32')

In [10]:
num2

array(['praju', '26', '45', '65', '35', '0.45'], dtype='<U32')

In [11]:
num2[1]

'26'

In [12]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [14]:
np.arange(1,2,0.15)

array([1.  , 1.15, 1.3 , 1.45, 1.6 , 1.75, 1.9 ])

In [15]:
num+10

array([23, 66, 44, 88, 20])

In [16]:
num3 = np.array([12, 45, 67, 11, 10])

In [17]:
num+num3

array([ 25, 101, 101,  89,  20])

# 2d arrays

In [19]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[12,45,10]])

In [20]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [12, 45, 10]])

In [21]:
arr.ndim

2

In [22]:
arr.shape

(4, 3)

In [23]:
arr.size

12

In [24]:
arr.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 12, 45, 10]])

In [25]:
arr.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 12],
       [45, 10]])

In [26]:
arr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 12, 45, 10])

In [27]:
arr.reshape(3,2,2)    # reshape array 2 dimentinal into 3 dimensional 

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 12],
        [45, 10]]])

In [29]:
arr.ndim

2

In [31]:
arr.reshape(2,-1) 

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 12, 45, 10]])

In [33]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [12, 45, 10]])

In [35]:
arr1 = ([[1,2,3],[4,5,6],[7,8,9]])
arr2 = ([[1,12,3],[14,35,6],[27,18,9]])

In [37]:
np.linalg.det(arr1)

6.66133814775094e-16

In [39]:
np.dot(arr1,arr2)

array([[110, 136,  42],
       [236, 331,  96],
       [362, 526, 150]])

In [41]:
np.linalg.inv(arr1)

array([[-4.50359963e+15,  9.00719925e+15, -4.50359963e+15],
       [ 9.00719925e+15, -1.80143985e+16,  9.00719925e+15],
       [-4.50359963e+15,  9.00719925e+15, -4.50359963e+15]])

In [43]:
np.diagonal(arr)

array([1, 5, 9])

In [47]:
#help(np)